
[env:esp32cam]

platform = espressif32@1.12.4  ; This version uses the needed 1.0.4 Arduino Core
board = esp32cam
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build Flags to ensure the camera and face detection headers are found
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -I lib/esp-face/include

lib_deps =
    ; PWM Servo Driver
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    
    ; Display Libraries
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.10
    
    ; Websockets Library 
    gilmaimon/ArduinoWebsockets @ ^0.5.3

    ; 
